/**
 * Configuration for all form/submission import modals.
 * Each plugin only needs a config entry — no separate component file.
 */

// ─── FORM IMPORT CONFIGS ────────────────────────────────────────────
// Used by FormImportModal.jsx — "select forms → import structure"

export const FORM_IMPORT_CONFIGS = {
  cf7: {
    fetchPath: '/qoracrm/v1/forms/cf7',
    importPath: '/qoracrm/v1/forms/cf7/import',
    idParam: 'cf7_id',
    parseId: (id) => parseInt(id, 10),
    successCheck: (response) => response && response.id,
    titleKey: 'import_from_cf7',
    titleFallback: 'Import from Contact Form 7',
    descKey: 'cf7_bulk_import_desc',
    descFallback: 'Select the forms you want to import. We will automatically map standard fields to the QoraCRM form builder.',
    errorFetchKey: 'error_fetching_cf7',
    errorFetchFallback: 'Failed to fetch CF7 forms.',
    noFormsKey: 'cf7_no_forms',
    noFormsFallback: 'No CF7 forms found on this site.',
    successKey: 'cf7_import_success_multiple',
    errorKey: 'cf7_import_error',
    errorFallback: 'Failed to import forms.',
  },
  elementor: {
    fetchPath: '/qoracrm/v1/forms/elementor',
    importPath: '/qoracrm/v1/forms/elementor/import',
    idParam: 'elementor_id',
    successCheck: (response) => response && response.id,
    titleKey: 'import_from_elementor',
    titleFallback: 'Import from Elementor Forms',
    descKey: 'elementor_bulk_import_desc',
    descFallback: 'Select the forms you want to import. We will automatically map standard fields to the QoraCRM form builder.',
    errorFetchKey: 'error_fetching_elementor',
    errorFetchFallback: 'Failed to fetch Elementor Forms.',
    noFormsKey: 'elementor_no_forms',
    noFormsFallback: 'No Elementor Forms found on this site.',
    successKey: 'elementor_import_success_multiple',
    errorKey: 'elementor_import_error',
    errorFallback: 'Failed to import forms.',
  },
  fluentforms: {
    fetchPath: '/qoracrm/v1/forms/fluent',
    importPath: '/qoracrm/v1/forms/fluent/import',
    idParam: 'fluent_id',
    successCheck: (response) => response && response.id,
    titleKey: 'import_from_fluent',
    titleFallback: 'Import from Fluent Forms',
    descKey: 'fluent_bulk_import_desc',
    descFallback: 'Select the forms you want to import. We will automatically map standard fields to the QoraCRM form builder.',
    errorFetchKey: 'error_fetching_fluent',
    errorFetchFallback: 'Failed to fetch Fluent Forms.',
    noFormsKey: 'fluent_no_forms',
    noFormsFallback: 'No Fluent Forms found on this site.',
    successKey: 'fluent_import_success_multiple',
    errorKey: 'fluent_import_error',
    errorFallback: 'Failed to import forms.',
  },
  gravity_forms: {
    fetchPath: '/qoracrm/v1/forms/gravity',
    importPath: '/qoracrm/v1/forms/gravity/import',
    idParam: 'gravity_id',
    successCheck: (response) => response && response.id,
    titleKey: 'import_from_gravity',
    titleFallback: 'Import from Gravity Forms',
    descKey: 'gravity_bulk_import_desc',
    descFallback: 'Select the forms you want to import. We will automatically map standard fields to the QoraCRM form builder.',
    errorFetchKey: 'error_fetching_gravity',
    errorFetchFallback: 'Failed to fetch Gravity Forms.',
    noFormsKey: 'gravity_no_forms',
    noFormsFallback: 'No Gravity Forms found on this site.',
    successKey: 'gravity_import_success_multiple',
    errorKey: 'gravity_import_error',
    errorFallback: 'Failed to import forms.',
  },
  wpforms: {
    fetchPath: '/qoracrm/v1/import/wpforms/forms',
    importPath: '/qoracrm/v1/import/wpforms/form',
    idParam: 'wpforms_id',
    successCheck: (response) => response && response.id,
    titleKey: 'import_from_wpforms',
    titleFallback: 'Import from WPForms',
    descKey: 'wpforms_bulk_import_desc',
    descFallback: 'Select the forms you want to import. We will automatically map standard fields to the QoraCRM form builder.',
    errorFetchKey: 'error_fetching_wpforms',
    errorFetchFallback: 'Failed to fetch WPForms.',
    noFormsKey: 'wpforms_no_forms',
    noFormsFallback: 'No WPForms found on this site.',
    successKey: 'wpforms_import_success_multiple',
    errorKey: 'wpforms_import_error',
    errorFallback: 'Failed to import forms.',
  },
  ninja_forms: {
    fetchPath: '/qoracrm/v1/import/ninja/forms',
    importPath: '/qoracrm/v1/import/ninja/form',
    idParam: 'ninja_id',
    successCheck: (response) => response && response.form_id !== undefined && response.success !== false,
    titleKey: 'import_from_ninja',
    titleFallback: 'Import from Ninja Forms',
    descKey: 'ninja_bulk_import_desc',
    descFallback: 'Select the forms you want to import. We will automatically map standard fields to the QoraCRM form builder.',
    errorFetchKey: 'error_fetching_ninja',
    errorFetchFallback: 'Failed to fetch Ninja Forms.',
    noFormsKey: 'no_ninja_forms',
    noFormsFallback: 'No Ninja Forms found on this site.',
    successKey: 'ninja_import_success_multiple',
    errorKey: 'ninja_import_error',
    errorFallback: 'Failed to import forms.',
    showFormIdFallback: true,
  },
  formidable: {
    fetchPath: '/qoracrm/v1/import/formidable/forms',
    importPath: '/qoracrm/v1/import/formidable/form',
    idParam: 'formidable_id',
    successCheck: (response) => response && response.form_id !== undefined && response.success !== false,
    titleKey: 'import_from_formidable',
    titleFallback: 'Import from Formidable Forms',
    descKey: 'formidable_bulk_import_desc',
    descFallback: 'Select the forms you want to import. We will automatically map standard fields to the QoraCRM form builder.',
    errorFetchKey: 'error_fetching_formidable',
    errorFetchFallback: 'Failed to fetch Formidable Forms.',
    noFormsKey: 'no_formidable_forms',
    noFormsFallback: 'No Formidable Forms found on this site.',
    successKey: 'formidable_import_success_multiple',
    errorKey: 'formidable_import_error',
    errorFallback: 'Failed to import forms.',
    showFormIdFallback: true,
  },
  forminator: {
    fetchPath: '/qoracrm/v1/import/forminator/forms',
    importPath: '/qoracrm/v1/import/forminator/form',
    idParam: 'forminator_id',
    successCheck: (response) => response && response.form_id !== undefined && response.success !== false,
    titleKey: 'import_from_forminator',
    titleFallback: 'Import from Forminator Forms',
    descKey: 'forminator_bulk_import_desc',
    descFallback: 'Select the forms you want to import. We will automatically map standard fields to the QoraCRM form builder.',
    errorFetchKey: 'error_fetching_forminator',
    errorFetchFallback: 'Failed to fetch Forminator Forms.',
    noFormsKey: 'no_forminator_forms',
    noFormsFallback: 'No Forminator Forms found on this site.',
    successKey: 'forminator_import_success_multiple',
    errorKey: 'forminator_import_error',
    errorFallback: 'Failed to import forms.',
    showFormIdFallback: true,
  },
  sureforms: {
    fetchPath: '/qoracrm/v1/import/sureforms/forms',
    importPath: '/qoracrm/v1/import/sureforms/form',
    idParam: 'sureforms_id',
    successCheck: (response) => response && response.form_id !== undefined && response.success !== false,
    titleKey: 'import_from_sureforms',
    titleFallback: 'Import from SureForms',
    descKey: 'sureforms_bulk_import_desc',
    descFallback: 'Select the forms you want to import. We will automatically map standard fields to the QoraCRM form builder.',
    errorFetchKey: 'error_fetching_sureforms',
    errorFetchFallback: 'Failed to fetch SureForms Forms.',
    noFormsKey: 'no_sureforms_forms',
    noFormsFallback: 'No SureForms found on this site.',
    successKey: 'sureforms_import_success_multiple',
    errorKey: 'sureforms_import_error',
    errorFallback: 'Failed to import forms.',
    showFormIdFallback: true,
  },
};


// ─── SUBMISSIONS IMPORT CONFIGS ─────────────────────────────────────
// Used by SubmissionsImportModal.jsx — "select source form → map fields → import leads"
// Two field formats:
//   'string'  — fields are plain strings (Flamingo, Elementor)
//   'object'  — fields are {id, label, key?} objects (WPForms, SureForms, etc.)

export const SUBMISSIONS_IMPORT_CONFIGS = {
  // Flamingo is special: uses channels instead of source form selection
  flamingo: {
    icon: '🦩',
    titleKey: 'import_flamingo',
    titleFallback: 'Import from Flamingo',
    descKey: 'import_flamingo_desc',
    descFallback: 'Import submissions from Flamingo into QoraCRM.',
    useChannels: true,
    fetchChannelsPath: '/qoracrm/v1/import/flamingo/channels',
    fetchFieldsPath: '/qoracrm/v1/import/flamingo/fields',
    fetchFieldsParam: 'channel',
    executePath: '/qoracrm/v1/import/flamingo/execute',
    executeIdParam: 'channel',
    fieldFormat: 'string',
    sourceColumnLabel: 'Flamingo Field',
    errorFetchKey: 'error_loading_flamingo',
    errorFetchFallback: 'Failed to load Flamingo channels',
    noDataKey: 'flamingo_no_data',
    noDataFallback: 'No Flamingo submissions found in the database. Are you sure Flamingo is installed and has data?',
  },
  elementor_leads: {
    icon: '🌀',
    titleKey: 'import_elementor_leads',
    titleFallback: 'Import Elementor Submissions',
    descKey: 'import_elementor_leads_desc',
    descFallback: 'Select the source Elementor form and the target QoraCRM form to import past submissions into the CRM.',
    sourceFormsPath: '/qoracrm/v1/forms/elementor',
    statsPath: '/qoracrm/v1/import/elementor/stats',
    statsParam: 'elementor_id',
    statsCountField: 'count',
    fieldsPath: '/qoracrm/v1/import/elementor/fields',
    fieldsParam: 'elementor_id',
    executePath: '/qoracrm/v1/import/elementor/execute',
    executeIdParam: 'elementor_id',
    fieldFormat: 'string',
    sourceColumnLabel: 'Elementor Field',
    sourceFormLabel: 'Source: Elementor Form',
    errorFetchKey: 'error_fetching_elementor',
    errorFetchFallback: 'Failed to load Elementor forms',
    noSubmissionsKey: 'elementor_no_submissions',
    noSubmissionsFallback: 'No submissions found for this form.',
  },
  fluentforms_leads: {
    icon: '📝',
    titleKey: 'import_fluent_leads',
    titleFallback: 'Import Fluent Forms Submissions',
    descKey: 'import_fluent_leads_desc',
    descFallback: 'Select the source Fluent Forms form and the target QoraCRM form to import past submissions into the CRM.',
    sourceFormsPath: '/qoracrm/v1/import/fluent/forms',
    statsPath: '/qoracrm/v1/import/fluent/stats',
    statsParam: 'fluent_id',
    statsCountField: 'count',
    fieldsPath: '/qoracrm/v1/import/fluent/fields',
    fieldsParam: 'fluent_id',
    executePath: '/qoracrm/v1/import/fluent/execute',
    executeIdParam: 'fluent_id',
    fieldFormat: 'string',
    sourceColumnLabel: 'Fluent Forms Field',
    sourceFormLabel: 'Source: Fluent Forms Form',
    errorFetchKey: 'error_fetching_fluent',
    errorFetchFallback: 'Failed to load Fluent Forms',
    noSubmissionsKey: 'fluent_no_submissions',
    noSubmissionsFallback: 'No submissions found for this form.',
  },
  gravity_leads: {
    icon: '🚀',
    titleKey: 'import_gravity_leads',
    titleFallback: 'Import Gravity Forms Submissions',
    descKey: 'import_gravity_leads_desc',
    descFallback: 'Select the source Gravity form and the target QoraCRM form to import past submissions into the CRM.',
    sourceFormsPath: '/qoracrm/v1/import/gravity/forms',
    statsPath: '/qoracrm/v1/import/gravity/stats',
    statsParam: 'gravity_id',
    statsCountField: 'count',
    fieldsPath: '/qoracrm/v1/import/gravity/fields',
    fieldsParam: 'gravity_id',
    executePath: '/qoracrm/v1/import/gravity/execute',
    executeIdParam: 'gravity_id',
    fieldFormat: 'string',
    sourceColumnLabel: 'Gravity Forms Field',
    sourceFormLabel: 'Source: Gravity Forms Form',
    errorFetchKey: 'error_fetching_gravity',
    errorFetchFallback: 'Failed to load Gravity Forms',
    noSubmissionsKey: 'gravity_no_submissions',
    noSubmissionsFallback: 'No submissions found for this form.',
  },
  wpforms_leads: {
    icon: '🐻',
    titleKey: 'import_wpforms_leads',
    titleFallback: 'Import WPForms Forms Submissions',
    descKey: 'import_wpforms_leads_desc',
    descFallback: 'Select the source WPForms Form and the target QoraCRM form to import past submissions into the CRM.',
    sourceFormsPath: '/qoracrm/v1/import/wpforms/forms',
    statsPath: '/qoracrm/v1/import/wpforms/stats',
    statsParam: 'wpforms_id',
    statsCountField: 'count',
    fieldsPath: '/qoracrm/v1/import/wpforms/fields',
    fieldsParam: 'wpforms_id',
    executePath: '/qoracrm/v1/import/wpforms/execute',
    executeIdParam: 'wpforms_id',
    fieldFormat: 'object', // fields are {key, label}
    fieldIdKey: 'key',
    fieldLabelKey: 'label',
    sourceColumnLabel: 'WPForms Field',
    sourceFormLabel: 'Source: WPForms Form',
    errorFetchKey: 'error_fetching_wpforms',
    errorFetchFallback: 'Failed to load WPForms forms',
    noSubmissionsKey: 'wpforms_no_submissions',
    noSubmissionsFallback: 'No submissions found for this form.',
    // WPForms uses parseComplexFieldValue for examples
    useComplexExamples: true,
  },
  ninja_leads: {
    icon: '🥷',
    titleKey: 'import_ninja_leads',
    titleFallback: 'Import Ninja Forms Submissions',
    descKey: 'import_ninja_leads_desc',
    descFallback: 'Select the source Ninja Forms form and the target QoraCRM form to import past submissions into the CRM.',
    sourceFormsPath: '/qoracrm/v1/import/ninja/forms',
    statsPath: '/qoracrm/v1/import/ninja/stats',
    statsParam: 'ninja_id',
    statsCountField: 'count',
    fieldsPath: '/qoracrm/v1/import/ninja/fields',
    fieldsParam: 'ninja_id',
    executePath: '/qoracrm/v1/import/ninja/execute',
    executeIdParam: 'ninja_id',
    fieldFormat: 'string',
    sourceColumnLabel: 'Ninja Forms Field',
    sourceFormLabel: 'Source: Ninja Forms Form',
    errorFetchKey: 'error_fetching_ninja',
    errorFetchFallback: 'Failed to load Ninja Forms',
    noSubmissionsKey: 'ninja_no_submissions',
    noSubmissionsFallback: 'No submissions found for this form.',
  },
  formidable_leads: {
    icon: '📋',
    titleKey: 'import_formidable_leads',
    titleFallback: 'Import Formidable Forms Submissions',
    descKey: 'import_formidable_leads_desc',
    descFallback: 'Select the source Formidable form and the target QoraCRM form to import past submissions into the CRM.',
    sourceFormsPath: '/qoracrm/v1/import/formidable/forms',
    statsPath: '/qoracrm/v1/import/formidable/stats',
    statsParam: 'formidable_id',
    statsCountField: 'count',
    fieldsPath: '/qoracrm/v1/import/formidable/fields',
    fieldsParam: 'formidable_id',
    executePath: '/qoracrm/v1/import/formidable/execute',
    executeIdParam: 'formidable_id',
    fieldFormat: 'string',
    sourceColumnLabel: 'Formidable Field',
    sourceFormLabel: 'Source: Formidable Forms Form',
    errorFetchKey: 'error_fetching_formidable',
    errorFetchFallback: 'Failed to load Formidable Forms',
    noSubmissionsKey: 'formidable_no_submissions',
    noSubmissionsFallback: 'No submissions found for this form.',
  },
  forminator_leads: {
    icon: '🦸',
    titleKey: 'import_forminator_leads',
    titleFallback: 'Import Forminator Submissions',
    descKey: 'import_forminator_leads_desc',
    descFallback: 'Select the source Forminator form and the target QoraCRM form to import past submissions into the CRM.',
    sourceFormsPath: '/qoracrm/v1/import/forminator/forms',
    statsPath: '/qoracrm/v1/import/forminator/stats',
    statsParam: 'forminator_id',
    statsCountField: 'count',
    fieldsPath: '/qoracrm/v1/import/forminator/fields',
    fieldsParam: 'forminator_id',
    executePath: '/qoracrm/v1/import/forminator/execute',
    executeIdParam: 'forminator_id',
    fieldFormat: 'string',
    sourceColumnLabel: 'Forminator Field',
    sourceFormLabel: 'Source: Forminator Form',
    errorFetchKey: 'error_fetching_forminator',
    errorFetchFallback: 'Failed to load Forminator Forms',
    noSubmissionsKey: 'forminator_no_submissions',
    noSubmissionsFallback: 'No submissions found for this form.',
  },
  sureforms_leads: {
    icon: '✨',
    titleKey: 'import_from_sureforms',
    titleFallback: 'Import from SureForms',
    descKey: 'sureforms_import_desc',
    descFallback: 'Select the source SureForms Form and the target QoraCRM form to import past submissions into the CRM.',
    sourceFormsPath: '/qoracrm/v1/import/sureforms/forms',
    statsPath: '/qoracrm/v1/import/sureforms/stats',
    statsParam: 'sureforms_id',
    statsCountField: 'total',
    fieldsPath: '/qoracrm/v1/import/sureforms/fields',
    fieldsParam: 'sureforms_id',
    executePath: '/qoracrm/v1/import/sureforms/execute',
    executeIdParam: 'sureforms_id',
    fieldFormat: 'object', // fields are {id, label, example?}
    fieldIdKey: 'id',
    fieldLabelKey: 'label',
    sourceColumnLabel: 'SureForms Field',
    sourceFormLabel: 'Source: SureForms Form',
    sourceFormShowId: true,
    errorFetchKey: 'error_fetching_sureforms',
    errorFetchFallback: 'Failed to load SureForms Forms',
    noSubmissionsKey: 'sureforms_no_submissions',
    noSubmissionsFallback: 'No submissions found for this form.',
    // SureForms has examples embedded in field objects
    useObjectExamples: true,
  },
};
